language: go
os:
  - linux
  - osx

go:
  #- "1.11.4"
  - "1.14"

before_install:
  - bash --version ; type bash
  # hack for speedup on mac build with our own bash5
  - ./travis/get_bash5_macos.sh
  - ./travis/get_bats-core.sh
  - go get github.com/docopt/docopt-go
  # get our official repos too
  - go get github.com/docopt/docopts

branches:
  only:
    - docopts-go
    - master

notifications:
  email:
    on_success: never

script:
  - make test

after_script:
  # using reverse_ssh_tunnel in after_script:
  # according to https://blog.travis-ci.com/after_script_behavior_changes/
  # not called if before_install: fails.
  # this should be run failure too
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then bash -x ./travis/reverse_ssh_tunnel.sh ; fi

